name: CI

on: 
  create:
    tags:
      - '*'

jobs:
  build-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go mod download
    - name: Build CLI
      run: make cli
    - name: Archive production artifacts 
      uses: actions/upload-artifact@v2
      with:
        name: dist-cli
        path: dist/*

  build-gui:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go mod download
    - name: Install dependencies on Ubuntu
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev xorg-dev
    - name: Build GUI
      run: make gui
    - name: Get release info
      id: get_release
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data } = await github.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: context.ref.replace('refs/tags/', '')
          })
          return { id: data.id, upload_url: data.upload_url }
    - name: Upload Release Asset CLI MacOS
      id: upload-release-asset-cli-macos
      uses: actions/upload-release-asset@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ./dist/macos/certyclick_verify_cli
        asset_name: certyclick_verify_cli_macos
        asset_content_type: application/octet-stream
    - name: Upload Release Asset CLI Windows
      id: upload-release-asset-cli-windows
      uses: actions/upload-release-asset@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ./dist/windows/certyclick_verify_cli.exe
        asset_name: certyclick_verify_cli_windows.exe
        asset_content_type: application/octet-stream
    - name: Upload Release Asset CLI Linux
      id: upload-release-asset-cli-linux
      uses: actions/upload-release-asset@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ./dist/linux/certyclick_verify_cli
        asset_name: certyclick_verify_cli_linux
        asset_content_type: application/octet-stream
    - name: Upload Release Asset GUI
      id: upload-release-asset-gui
      uses: actions/upload-release-asset@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }} 
        asset_path: ./dist/certyclick_verify_gui
        asset_name: certyclick_verify_gui_${{ matrix.os }}
        asset_content_type: application/octet-stream
